### ISSUE TITLE
Unable to run find function

### ISSUE THREAD

**Issue by Fatima-Ali8765** [serengil/deepface#162]
I first installed deepface on colab using !pip install deepface only.
I then tried to run DeepID and Dlib as models for the find() function in colab but it gives me the following errors even though I mentioned all my parameters and paths correctly for the find function:
For DeepID:DeepFace.find(img_path = "/content/img1.jpg", db_path = "/content/my_db", model_name = "DeepID",enforce_detection=False,detector_backend="dlib")
    ValueError: Input 0 is incompatible with layer model: expected shape=(None, 55, 47, 3), found shape=(None, 47, 55, 3).

For Dlib:DeepFace.find(img_path = "/content/img1.jpg", db_path = "/content/my_db", model_name = "Dlib",enforce_detection=False,detector_backend="dlib") 
SystemError: new style getargs format but argument is not a tuple.

What is causing this error and what steps/alternate should I take to solve it?

**Comment by serengil** [comment]
Dlib is not a mandatory dependency. You have to install it if you want to use.

pip install dlib==19.20.0

For deepid trouble, it seems that i should fix it in the next release. I can do it in this week.

**Comment by serengil** [comment]
I updated the source code: https://github.com/serengil/deepface/commit/286d48395db52393b3a6fcb621096c669134fe8b

You can clone the latest code and solve this issue. I will publish it to the pip in the next days.

**Comment by Fatima-Ali8765** [comment]
OK.
Before your update, I tried to solve the issue of dlib. 
So I first installed the new dlib on colab using your command.
Then I installed deepface using pip install.
Then I tried to run the find function but oddly I am still getting the error.
I'll attach the error log below:
----> 4 df = DeepFace.find(img_path = "/content/img1.jpg", db_path = "/content/fdd", model_name = models[6],enforce_detection=False)

1 frames
/usr/local/lib/python3.6/dist-packages/deepface/DeepFace.py in find(img_path, db_path, model_name, distance_metric, model, enforce_detection, detector_backend)
    606 				img = functions.preprocess_face(img = img_path, target_size = input_shape
    607                                         , enforce_detection = enforce_detection
--> 608 					, detector_backend = detector_backend)
    609 
    610                                 target_representation = custom_model.predict(img)[0,:]

/usr/local/lib/python3.6/dist-packages/deepface/commons/functions.py in preprocess_face(img, target_size, grayscale, enforce_detection, detector_backend)
    464                 img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    465 
--> 466         img = cv2.resize(img, target_size)
    467         img_pixels = image.img_to_array(img)
    468         img_pixels = np.expand_dims(img_pixels, axis = 0)

SystemError: new style getargs format but argument is not a tuple

**Comment by serengil** [comment]
dlib is very problematic package. could you import it without any problem?

**Comment by Fatima-Ali8765** [comment]
Yes, I was able to import it on colab.

**Comment by serengil** [comment]
facenet and arcface are lightweight and stronger models than dlib. I recommend you to use those models.

**Comment by Fatima-Ali8765** [comment]
Ok got it.

**Comment by Fatima-Ali8765** [comment]
Why does the facebook deepface algorithm consumes alot of time?

**Comment by serengil** [comment]
it has a much complex structure than others.

**Comment by Fatima-Ali8765** [comment]
OK. Noted.

**Comment by serengil** [comment]
I mostly do not use facebook deepface model.
