### ISSUE TITLE
Realtime stream issue

### ISSUE THREAD

**Issue by KarasuY** [serengil/deepface#90]
Latest version (0.0.36) has issues with stream functionality. 
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
This issue was not present in version 0.0.35

**Comment by serengil** [comment]
my tests succeeded when I run stream function. Could you give some details. For example, how do you run the stream function (which arguments), this exception comes from where (which line of realtime.py).

**Comment by serengil** [comment]
Oke, I think I understand the problem. I've added new features for pre-processing stages (face detection and alignment) this weekend. That causes the problem. It must be resolved in 0.0.37 version. Please try and respond to this issue. Thanks

**Comment by mahamatnoumai** [comment]
I think there is still some issues on deepface 0.0.37 & 0.0.34 too, I keep trying different version but somehow stuck with this issues. 

`df = DeepFace.find(img_path='target.jpg', db_path='db/')`


I got similar error too. Even though I  pass enforce_detection argument as False to both verify and analze function in DeepFace.py.  the problem still there. 

<img width="1117" alt="Screenshot 2020-09-17 at 9 14 25 AM" src="https://user-images.githubusercontent.com/17758399/93408049-384ced00-f8c6-11ea-9d8d-89c4a33dec91.png">

**Comment by serengil** [comment]
Could you share the input image.

**Comment by safi-ai** [comment]
> Could you share the input image.
Thanks @serengil Fixed already.
